from enum import Enum


class ErrorCode(str, Enum):
    INVALID_REQUEST = "INVALID_REQUEST"
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
    LOW_ROUTER_CONFIDENCE = "LOW_ROUTER_CONFIDENCE"
    TOOL_SELECTOR_REQUIRED = "TOOL_SELECTOR_REQUIRED"
    UNSUPPORTED_ROUTE = "UNSUPPORTED_ROUTE"
    RISK_REJECTED = "RISK_REJECTED"
    CHECKPOINT_NOT_FOUND = "CHECKPOINT_NOT_FOUND"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    TOOL_EXECUTION_ERROR = "TOOL_EXECUTION_ERROR"
    DEPENDENCY_TIMEOUT = "DEPENDENCY_TIMEOUT"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
